version: '3.5'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - $HTTP_EXPOSING_PORT:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/config/php.ini:/etc/php/8.0/cli/php.ini
      - ./docker/config/www.conf:/etc/php/8.0/fpm/pool.d/www.conf
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/wp-config.php:/var/www/wp-config.php
      - ./docker/wordpress:/var/www/wordpress
      # - ./docker/php/php.ini:/etc/php/8.0/fpm/php.ini
      # - ./docker/php/php.ini:/etc/php/8.0/cli/php.ini
      # - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/zz-php-custom.ini
      # - ./vendor/johnpbloch/wordpress-core:/var/www/wordpress
      # - ./vendor/wp-plugin/woocommerce:/var/www/wordpress/wp-content/plugins/woocommerce
      # - ./vendor/wp-plugin/woo-checkout-field-editor-pro:/var/www/wordpress/wp-content/plugins/woo-checkout-field-editor-pro
      # - ./vendor/wp-theme/storefront:/var/www/wordpress/wp-content/themes/storefront
      # - ./docker/wordpress/wp-content/logs:/var/www/wordpress/wp-content/logs
      # - ./docker/wp-config.php:/var/www/wp-config.php
      # - ./:${PROJECT_MOUNT_PATH}
    env_file:
      - ./.env
    environment:
      - DB_CONNECTION
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOST
      - DB_USER
      - DB_NAME
      - PHP_SENDMAIL_PATH="/usr/sbin/sendmail -t -i"

  mysql8:
    image: mysql:8
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306
    volumes:
      - mysql_db:/var/lib/mysql
      # - './docker/mysql8/my.cnf:/etc/mysql/conf.d/my.cnf'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
volumes:
  mysql_db:
    