version: '3.5'

services:
  appserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 11080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
    #   - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #   - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    #   - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/zz-php-custom.ini
      - ./vendor/johnpbloch/wordpress-core:/var/www/wordpress
    #   - ./vendor/wp-plugin/woocommerce:/var/www/wordpress/wp-content/plugins/woocommerce
    #   - ./vendor/wp-plugin/woo-checkout-field-editor-pro:/var/www/wordpress/wp-content/plugins/woo-checkout-field-editor-pro
    #   - ./vendor/wp-theme/storefront:/var/www/wordpress/wp-content/themes/storefront
    #   - ./docker/wordpress/wp-content/logs:/var/www/wordpress/wp-content/logs
      - ./docker/wordpress/wp-config.php:/var/www/wp-config.php
    #   - ./:${PROJECT_MOUNT_PATH}
    env_file:
      - ./.env
    environment:
      DB_CONNECTION:
      DB_PORT:
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      # PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST:
      DB_USER:
      DB_NAME: